all_plan:
    path: /plan/all
    controller: App\Application\Controller\Api\V1\TravelController::allPlan
    methods: [POST]

itinerary:
    path: /plan/itinerary
    controller: App\Application\Controller\Api\V1\TravelController::itinerary
    methods: [POST]

climate_information:
    path: /information/climate
    controller: App\Application\Controller\Api\V1\TravelController::climateInformation
    methods: [POST]

safety_information:
    path: /information/safety
    controller: App\Application\Controller\Api\V1\TravelController::safetyInformation
    methods: [POST]